include: package:night_raven_insight/analysis_options.yaml

linter:
  rules:
    - await_only_futures
    - discarded_futures
    - switch_on_type
    - unawaited_futures
    - unnecessary_async
    - unnecessary_parenthesis
    - unnecessary_unawaited

formatter:
  trailing_commas: preserve
